In [1]:
import pandas as pd

In [2]:
import numpy as np

In [4]:
data = pd.read_csv(r"C:\\Users\\Sawpanil\\Downloads\\archive (5)\\WA_Fn-UseC_-Telco-Customer-Churn.csv")

In [22]:
data.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,0,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,0
1,5575-GNVDE,1,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.50,0
2,3668-QPYBK,1,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,1
3,7795-CFOCW,1,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,0
4,9237-HQITU,0,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,1

In [8]:
data.describe(include='all')

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
count,7043,7043,7043.000000,7043,7043,7043.000000,7043,7043,7043,7043,...,7043,7043,7043,7043,7043,7043,7043,7043.000000,7043,7043
unique,7043,2,NaN,2,2,NaN,2,3,3,3,...,3,3,3,3,3,2,4,NaN,6531,2
top,3186-AJIEK,Male,NaN,No,No,NaN,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,NaN,20.2,No
freq,1,3555,NaN,3641,4933,NaN,6361,3390,3096,3498,...,3095,3473,2810,2785,3875,4171,2365,NaN,11,5174
mean,NaN,NaN,0.162147,NaN,NaN,32.371149,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,64.761692,NaN,NaN
std,NaN,NaN,0.368612,NaN,NaN,24.559481,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,30.090047,NaN,NaN
min,NaN,NaN,0.000000,NaN,NaN,0.000000,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18.250000,NaN,NaN
25%,NaN,NaN,0.000000,NaN,NaN,9.000000,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,35.500000,NaN,NaN
50%,NaN,NaN,0.000000,NaN,NaN,29.000000,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,70.350000,NaN,NaN
75%,NaN,NaN,0.000000,NaN,NaN,55.000000,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,89.850000,NaN,NaN
max,NaN,NaN,1.000000,NaN,NaN,72.000000,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,118.750000,NaN,NaN

In [25]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   int64
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7032 non-null   float64
 20  Churn             7043 non-null   int64
dtypes: float64(2), int64(4), object(15)
memory usage: 1.1+ MB

In [11]:
data=pd.DataFrame(data)

In [15]:
data.duplicated().sum()

np.int64(0)

In [18]:
data['TotalCharges'] = pd.to_numeric(data['TotalCharges'], errors='coerce')

In [21]:
data['Churn'] = data['Churn'].map({'Yes':1, 'No':0})
data['gender'] = data['gender'].map({'Male':1, 'Female':0})

In [27]:
data.to_csv(r"C:\\Users\\Sawpanil\\Downloads\\clean_telecom1.csv",index= False)

In [26]:
data

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,0,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,0
1,5575-GNVDE,1,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.50,0
2,3668-QPYBK,1,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,1
3,7795-CFOCW,1,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,0
4,9237-HQITU,0,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,6840-RESVB,1,0,Yes,Yes,24,Yes,Yes,DSL,Yes,...,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.50,0
7039,2234-XADUH,0,0,Yes,Yes,72,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.90,0
7040,4801-JZAZL,0,0,Yes,Yes,11,No,No phone service,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,0
7041,8361-LTMKD,1,1,Yes,No,4,Yes,Yes,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.60,1
7042,3186-AJIEK,1,0,No,No,66,Yes,No,Fiber optic,Yes,...,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.50,0

In [29]:
import pandas as pd

# Load dataset


# Select required columns
customer_table = data[['customerID',
                     'gender',
                     'SeniorCitizen',
                     'Partner',
                     'Dependents']]

# Display first 5 rows
print(customer_table.head())


customer_table.to_csv(r"C:\\Users\\Sawpanil\\Downloads\\customer_table.csv", index=False)

   customerID  gender  SeniorCitizen Partner Dependents
0  7590-VHVEG       0              0     Yes         No
1  5575-GNVDE       1              0      No         No
2  3668-QPYBK       1              0      No         No
3  7795-CFOCW       1              0      No         No
4  9237-HQITU       0              0      No         No

In [34]:
import pandas as pd

# Load dataset


# Create Service / Plan dimension table
service_table = data[['customerID',
                    'PhoneService',
                    'MultipleLines',
                    'InternetService',
                    'OnlineSecurity',
                    'OnlineBackup',
                    'DeviceProtection',
                    'TechSupport',
                    'StreamingTV',
                    'StreamingMovies',
                    'Contract',
                    'PaperlessBilling',
                    'PaymentMethod']].copy()
service_table.replace({
    'No internet service': 'No',
    'No phone service': 'No'
}, inplace=True)


# Preview
print(service_table.head())

# Save as new CSV file
service_table.to_csv(r"C:\\Users\\Sawpanil\\Downloads\\service_plan_table.csv", index=False)

   customerID PhoneService MultipleLines InternetService OnlineSecurity  \
0  7590-VHVEG           No            No             DSL             No
1  5575-GNVDE          Yes            No             DSL            Yes
2  3668-QPYBK          Yes            No             DSL            Yes
3  7795-CFOCW           No            No             DSL            Yes
4  9237-HQITU          Yes            No     Fiber optic             No

  OnlineBackup DeviceProtection TechSupport StreamingTV StreamingMovies  \
0          Yes               No          No          No              No
1           No              Yes          No          No              No
2          Yes               No          No          No              No
3           No              Yes         Yes          No              No
4           No               No          No          No              No

         Contract PaperlessBilling              PaymentMethod
0  Month-to-month              Yes           Electronic check
1        One year               No               Mailed check
2  Month-to-month              Yes               Mailed check
3        One year               No  Bank transfer (automatic)
4  Month-to-month              Yes           Electronic check

In [35]:
import pandas as pd

# Load dataset


# Create Billing & Usage fact table
billing_table = data[['customerID',
                    'tenure',
                    'MonthlyCharges',
                    'TotalCharges',
                    'Churn']].copy()

# Handle missing TotalCharges (11 null values)
billing_table['TotalCharges'] = billing_table['TotalCharges'].fillna(0)

# Optional: Convert Churn from 0/1 to Yes/No
billing_table['Churn'] = billing_table['Churn'].map({0: 'No', 1: 'Yes'})

# Preview
print(billing_table.head())

# Save as new CSV file
billing_table.to_csv(r"C:\\Users\\Sawpanil\\Downloads\\billing_usage_table.csv", index=False)

   customerID  tenure  MonthlyCharges  TotalCharges Churn
0  7590-VHVEG       1           29.85         29.85    No
1  5575-GNVDE      34           56.95       1889.50    No
2  3668-QPYBK       2           53.85        108.15   Yes
3  7795-CFOCW      45           42.30       1840.75    No
4  9237-HQITU       2           70.70        151.65   Yes